In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv('RESULT_Sheet1.csv')

In [3]:
df

,DataSets,B-R,B-MA,B-MP,C-R,C-MA,C-MP,G-R,G-MA,G-MP,...,S-MP,C_B-R,C_B-MA,C_B-MP,C_L-R,C_L-MA,C_L-MP,G_B-R,G_B-MA,G_B-MP
0,BHIWADI,23.130568,16.608184,0.433944,57.202086,53.935064,1.343076,22.337377,15.584919,0.484164,...,0.962300,45.981685,39.662920,1.112111,43.502916,40.295271,1.057512,35.295456,23.058272,0.631133
1,JODHPUR,27.537045,19.713489,0.311956,27.228193,20.202762,0.271624,34.335825,24.928492,0.402936,...,0.553217,40.871624,29.348479,0.443007,43.546570,32.465213,0.546886,52.628164,38.122879,0.571144
2,SINGRAULI,10.924705,7.016597,0.610730,15.496583,10.490691,0.663373,27.342745,25.994662,2.126799,...,1.056676,50.606150,49.156799,3.565068,22.202998,20.966438,1.719301,26.501040,24.552270,2.029104
3,ANKLESHWAR,18.531004,13.301683,0.145049,16.679045,12.167558,0.130342,37.148811,30.311750,0.251620,...,0.311937,62.854788,51.311231,0.404935,68.721722,57.525183,0.458844,69.376777,58.267578,0.465858
4,LUDHIANA,8.396340,6.133704,0.150839,11.118954,9.054776,0.281483,22.141513,17.495035,0.572891,...,0.427379,25.659122,20.930398,0.710819,24.758328,19.838622,0.660466,23.767473,18.025209,0.512238
5,DURGAPUR,6.141876,4.472633,0.283394,8.272925,6.226658,0.511795,20.339084,19.322128,0.933893,...,0.837774,9.617848,7.321162,0.660868,13.755351,12.599410,0.720911,24.390621,21.967310,1.378542
6,YAMUNA_NAGAR,37.344312,17.049220,0.227051,34.566169,17.730612,0.260001,56.266320,31.741383,0.326976,...,0.531978,72.391328,42.248065,0.474423,45.625861,23.310026,0.321738,74.133820,43.989555,0.469857
7,CHARKHI_DADRI,18.421645,11.657644,0.482551,20.425081,14.515600,0.751753,27.956190,19.908345,0.750988,...,1.122814,46.163078,35.004722,2.084889,45.268197,33.340354,1.876119,43.484554,33.000633,1.946915
8,JIND,24.168184,15.283933,0.154443,26.418045,17.459934,0.214926,34.348801,23.740109,0.302014,...,0.475597,62.128675,46.760649,0.385177,43.592608,27.886940,0.228332,50.945754,33.973918,0.301961
9,KURUKSHETRA,27.140688,13.831852,0.187149,72.028463,45.504528,0.403442,43.561329,24.773557,0.265006,...,0.509026,39.705229,24.426961,0.336589,88.118807,53.829761,0.542060,53.735560,32.164865,0.309342
10,SONIPAT,12.557539,7.049970,0.157003,15.983048,9.535769,0.175188,22.404111,15.089826,0.356836,...,0.584195,24.010694,14.683013,0.325027,22.957801,13.654510,0.241921,46.774394,29.122356,0.378513
11,DHARUHERA,26.740801,11.924181,0.301372,28.928955,17.222860,0.580640,34.604395,17.800501,0.411377,...,0.870132,31.926598,16.987909,0.517577,35.012949,18.797340,0.376532,46.222202,25.449881,0.516237
12,AMBALA,22.584264,13.033090,0.288949,28.959282,17.008473,0.476215,41.081808,22.048210,0.421885,...,0.865842,40.709394,24.824555,0.408685,34.138273,19.511029,0.490696,63.853459,37.186576,0.826289
13,HISAR,28.343300,12.304253,0.131857,66.792668,45.695764,0.312662,47.934032,29.603868,0.227257,...,0.387485,43.156967,27.527658,0.321203,49.102246,30.514601,0.282734,62.459927,41.180306,0.305030
14,FATEHABAD,14.368081,8.644485,0.130928,38.361204,29.694122,0.354418,72.709026,45.760330,0.500245,...,0.442260,74.375532,47.321480,0.607125,76.747551,48.299882,0.566495,72.640963,46.981820,0.647896
15,BULANDSHAHR,7.386808,4.761442,0.289845,8.870220,7.381033,0.598783,19.790344,19.148556,1.348094,...,0.988747,9.605320,7.276044,0.614124,13.157847,11.811171,0.973559,11.507966,8.210321,0.561416
16,MUZAFFARNAGAR,11.876729,8.226995,0.299563,16.129485,12.646917,0.619487,13.724172,11.259948,0.589981,...,0.675373,15.911830,12.904264,0.690320,23.603618,21.327213,1.106398,21.895328,18.490387,0.969023

In [4]:
df1=pd.read_csv('RESULT_Sheet1.csv',usecols={'DataSets','B-MA','C-MA','G-MA','SS-MA','V-MA','S-MA','C_B-MA','C_L-MA','G_B-MA'})

In [5]:
df1=df1.rename(columns={'B-MA':'BiLSTM','C-MA':'CNN','G-MA':'GRU','SS-MA':'Seq2Seq','V-MA':'V-LSTM','S-MA':'S_LSTM','C_B-MA':'CNN_BiLSTM','C_L-MA':'CNN_LSTM','G_B-MA':'GRU_BiLSTM'})
#df1=df1.set_index('DateSets')
df1

,DataSets,BiLSTM,CNN,GRU,Seq2Seq,V-LSTM,S_LSTM,CNN_BiLSTM,CNN_LSTM,GRU_BiLSTM
0,BHIWADI,16.608184,53.935064,15.584919,17.053743,12.350437,34.314668,39.662920,40.295271,23.058272
1,JODHPUR,19.713489,20.202762,24.928492,17.513632,14.301373,35.722443,29.348479,32.465213,38.122879
2,SINGRAULI,7.016597,10.490691,25.994662,19.484450,11.791581,13.176164,49.156799,20.966438,24.552270
3,ANKLESHWAR,13.301683,12.167558,30.311750,18.869534,13.777352,37.084015,51.311231,57.525183,58.267578
4,LUDHIANA,6.133704,9.054776,17.495035,7.733355,6.949968,15.973876,20.930398,19.838622,18.025209
5,DURGAPUR,4.472633,6.226658,19.322128,7.379266,7.813348,11.749026,7.321162,12.599410,21.967310
6,YAMUNA_NAGAR,17.049220,17.730612,31.741383,15.108928,17.860724,39.130530,42.248065,23.310026,43.989555
7,CHARKHI_DADRI,11.657644,14.515600,19.908345,11.384104,11.236602,30.324326,35.004722,33.340354,33.000633
8,JIND,15.283933,17.459934,23.740109,16.718722,11.463562,51.706200,46.760649,27.886940,33.973918
9,KURUKSHETRA,13.831852,45.504528,24.773557,16.825723,14.730810,42.259590,24.426961,53.829761,32.164865
10,SONIPAT,7.049970,9.535769,15.089826,9.033864,6.262973,26.948187,14.683013,13.654510,29.122356
11,DHARUHERA,11.924181,17.222860,17.800501,9.617720,10.611183,32.704655,16.987909,18.797340,25.449881
12,AMBALA,13.033090,17.008473,22.048210,11.214580,8.961461,34.417781,24.824555,19.511029,37.186576
13,HISAR,12.304253,45.695764,29.603868,19.541525,15.934216,41.060877,27.527658,30.514601,41.180306
14,FATEHABAD,8.644485,29.694122,45.760330,8.641448,9.372656,25.935523,47.321480,48.299882,46.981820
15,BULANDSHAHR,4.761442,7.381033,19.148556,9.013762,5.597348,11.847920,7.276044,11.811171,8.210321
16,MUZAFFARNAGAR,8.226995,12.646917,11.259948,11.676090,10.465821,16.645883,12.904264,21.327213,18.490387

In [6]:
df1.to_csv('MAE.csv')

In [7]:
import glob

In [8]:
import glob
all_f= glob.glob('*E.csv')
all_f

['MAPE.csv',
 '2ND EDA - MAPE.csv',
 '2ND EDA - MAE.csv',
 '2ND EDA - RMSE.csv',
 'MAE.csv',
 'RMSE.csv']

In [9]:
li=[]
for file_name in all_f:
    df=pd.read_csv(file_name)
    li.append(df)

In [10]:
li[4]

,Unnamed: 0,DataSets,BiLSTM,CNN,GRU,Seq2Seq,V-LSTM,S_LSTM,CNN_BiLSTM,CNN_LSTM,GRU_BiLSTM
0,0,BHIWADI,16.608184,53.935064,15.584919,17.053743,12.350437,34.314668,39.662920,40.295271,23.058272
1,1,JODHPUR,19.713489,20.202762,24.928492,17.513632,14.301373,35.722443,29.348479,32.465213,38.122879
2,2,SINGRAULI,7.016597,10.490691,25.994662,19.484450,11.791581,13.176164,49.156799,20.966438,24.552270
3,3,ANKLESHWAR,13.301683,12.167558,30.311750,18.869534,13.777352,37.084015,51.311231,57.525183,58.267578
4,4,LUDHIANA,6.133704,9.054776,17.495035,7.733355,6.949968,15.973876,20.930398,19.838622,18.025209
5,5,DURGAPUR,4.472633,6.226658,19.322128,7.379266,7.813348,11.749026,7.321162,12.599410,21.967310
6,6,YAMUNA_NAGAR,17.049220,17.730612,31.741383,15.108928,17.860724,39.130530,42.248065,23.310026,43.989555
7,7,CHARKHI_DADRI,11.657644,14.515600,19.908345,11.384104,11.236602,30.324326,35.004722,33.340354,33.000633
8,8,JIND,15.283933,17.459934,23.740109,16.718722,11.463562,51.706200,46.760649,27.886940,33.973918
9,9,KURUKSHETRA,13.831852,45.504528,24.773557,16.825723,14.730810,42.259590,24.426961,53.829761,32.164865
10,10,SONIPAT,7.049970,9.535769,15.089826,9.033864,6.262973,26.948187,14.683013,13.654510,29.122356
11,11,DHARUHERA,11.924181,17.222860,17.800501,9.617720,10.611183,32.704655,16.987909,18.797340,25.449881
12,12,AMBALA,13.033090,17.008473,22.048210,11.214580,8.961461,34.417781,24.824555,19.511029,37.186576
13,13,HISAR,12.304253,45.695764,29.603868,19.541525,15.934216,41.060877,27.527658,30.514601,41.180306
14,14,FATEHABAD,8.644485,29.694122,45.760330,8.641448,9.372656,25.935523,47.321480,48.299882,46.981820
15,15,BULANDSHAHR,4.761442,7.381033,19.148556,9.013762,5.597348,11.847920,7.276044,11.811171,8.210321
16,16,MUZAFFARNAGAR,8.226995,12.646917,11.259948,11.676090,10.465821,16.645883,12.904264,21.327213,18.490387

In [11]:
s_n=4
df2=li[s_n]
df2

,Unnamed: 0,DataSets,BiLSTM,CNN,GRU,Seq2Seq,V-LSTM,S_LSTM,CNN_BiLSTM,CNN_LSTM,GRU_BiLSTM
0,0,BHIWADI,16.608184,53.935064,15.584919,17.053743,12.350437,34.314668,39.662920,40.295271,23.058272
1,1,JODHPUR,19.713489,20.202762,24.928492,17.513632,14.301373,35.722443,29.348479,32.465213,38.122879
2,2,SINGRAULI,7.016597,10.490691,25.994662,19.484450,11.791581,13.176164,49.156799,20.966438,24.552270
3,3,ANKLESHWAR,13.301683,12.167558,30.311750,18.869534,13.777352,37.084015,51.311231,57.525183,58.267578
4,4,LUDHIANA,6.133704,9.054776,17.495035,7.733355,6.949968,15.973876,20.930398,19.838622,18.025209
5,5,DURGAPUR,4.472633,6.226658,19.322128,7.379266,7.813348,11.749026,7.321162,12.599410,21.967310
6,6,YAMUNA_NAGAR,17.049220,17.730612,31.741383,15.108928,17.860724,39.130530,42.248065,23.310026,43.989555
7,7,CHARKHI_DADRI,11.657644,14.515600,19.908345,11.384104,11.236602,30.324326,35.004722,33.340354,33.000633
8,8,JIND,15.283933,17.459934,23.740109,16.718722,11.463562,51.706200,46.760649,27.886940,33.973918
9,9,KURUKSHETRA,13.831852,45.504528,24.773557,16.825723,14.730810,42.259590,24.426961,53.829761,32.164865
10,10,SONIPAT,7.049970,9.535769,15.089826,9.033864,6.262973,26.948187,14.683013,13.654510,29.122356
11,11,DHARUHERA,11.924181,17.222860,17.800501,9.617720,10.611183,32.704655,16.987909,18.797340,25.449881
12,12,AMBALA,13.033090,17.008473,22.048210,11.214580,8.961461,34.417781,24.824555,19.511029,37.186576
13,13,HISAR,12.304253,45.695764,29.603868,19.541525,15.934216,41.060877,27.527658,30.514601,41.180306
14,14,FATEHABAD,8.644485,29.694122,45.760330,8.641448,9.372656,25.935523,47.321480,48.299882,46.981820
15,15,BULANDSHAHR,4.761442,7.381033,19.148556,9.013762,5.597348,11.847920,7.276044,11.811171,8.210321
16,16,MUZAFFARNAGAR,8.226995,12.646917,11.259948,11.676090,10.465821,16.645883,12.904264,21.327213,18.490387

In [12]:
v=all_f[s_n].split(r".")
#u=v[3].split(r' ')
Pre_Ds=v[0]
Pre_Ds

'MAE'

In [13]:
#df2=df2.drop('Unnamed: 0',axis=1)

In [14]:
df2=df2.set_index('DataSets')

In [15]:
df2=df2.round(decimals = 2)
df2

,Unnamed: 0,BiLSTM,CNN,GRU,Seq2Seq,V-LSTM,S_LSTM,CNN_BiLSTM,CNN_LSTM,GRU_BiLSTM
DataSets,,,,,,,,,,
BHIWADI,0,16.61,53.94,15.58,17.05,12.35,34.31,39.66,40.30,23.06
JODHPUR,1,19.71,20.20,24.93,17.51,14.30,35.72,29.35,32.47,38.12
SINGRAULI,2,7.02,10.49,25.99,19.48,11.79,13.18,49.16,20.97,24.55
ANKLESHWAR,3,13.30,12.17,30.31,18.87,13.78,37.08,51.31,57.53,58.27
LUDHIANA,4,6.13,9.05,17.50,7.73,6.95,15.97,20.93,19.84,18.03
DURGAPUR,5,4.47,6.23,19.32,7.38,7.81,11.75,7.32,12.60,21.97
YAMUNA_NAGAR,6,17.05,17.73,31.74,15.11,17.86,39.13,42.25,23.31,43.99
CHARKHI_DADRI,7,11.66,14.52,19.91,11.38,11.24,30.32,35.00,33.34,33.00
JIND,8,15.28,17.46,23.74,16.72,11.46,51.71,46.76,27.89,33.97
KURUKSHETRA,9,13.83,45.50,24.77,16.83,14.73,42.26,24.43,53.83,32.16
SONIPAT,10,7.05,9.54,15.09,9.03,6.26,26.95,14.68,13.65,29.12
DHARUHERA,11,11.92,17.22,17.80,9.62,10.61,32.70,16.99,18.80,25.45
AMBALA,12,13.03,17.01,22.05,11.21,8.96,34.42,24.82,19.51,37.19
HISAR,13,12.30,45.70,29.60,19.54,15.93,41.06,27.53,30.51,41.18
FATEHABAD,14,8.64,29.69,45.76,8.64,9.37,25.94,47.32,48.30,46.98
BULANDSHAHR,15,4.76,7.38,19.15,9.01,5.60,11.85,7.28,11.81,8.21
MUZAFFARNAGAR,16,8.23,12.65,11.26,11.68,10.47,16.65,12.90,21.33,18.49

In [16]:
df2.to_csv(Pre_Ds+'.csv')

In [17]:
df2=df2.round(decimals = 2)
df2

,Unnamed: 0,BiLSTM,CNN,GRU,Seq2Seq,V-LSTM,S_LSTM,CNN_BiLSTM,CNN_LSTM,GRU_BiLSTM
DataSets,,,,,,,,,,
BHIWADI,0,16.61,53.94,15.58,17.05,12.35,34.31,39.66,40.30,23.06
JODHPUR,1,19.71,20.20,24.93,17.51,14.30,35.72,29.35,32.47,38.12
SINGRAULI,2,7.02,10.49,25.99,19.48,11.79,13.18,49.16,20.97,24.55
ANKLESHWAR,3,13.30,12.17,30.31,18.87,13.78,37.08,51.31,57.53,58.27
LUDHIANA,4,6.13,9.05,17.50,7.73,6.95,15.97,20.93,19.84,18.03
DURGAPUR,5,4.47,6.23,19.32,7.38,7.81,11.75,7.32,12.60,21.97
YAMUNA_NAGAR,6,17.05,17.73,31.74,15.11,17.86,39.13,42.25,23.31,43.99
CHARKHI_DADRI,7,11.66,14.52,19.91,11.38,11.24,30.32,35.00,33.34,33.00
JIND,8,15.28,17.46,23.74,16.72,11.46,51.71,46.76,27.89,33.97
KURUKSHETRA,9,13.83,45.50,24.77,16.83,14.73,42.26,24.43,53.83,32.16
SONIPAT,10,7.05,9.54,15.09,9.03,6.26,26.95,14.68,13.65,29.12
DHARUHERA,11,11.92,17.22,17.80,9.62,10.61,32.70,16.99,18.80,25.45
AMBALA,12,13.03,17.01,22.05,11.21,8.96,34.42,24.82,19.51,37.19
HISAR,13,12.30,45.70,29.60,19.54,15.93,41.06,27.53,30.51,41.18
FATEHABAD,14,8.64,29.69,45.76,8.64,9.37,25.94,47.32,48.30,46.98
BULANDSHAHR,15,4.76,7.38,19.15,9.01,5.60,11.85,7.28,11.81,8.21
MUZAFFARNAGAR,16,8.23,12.65,11.26,11.68,10.47,16.65,12.90,21.33,18.49