In [1]:
import pandas as pd
import numpy as np
import glob
import time


from pycaret.time_series import *

In [2]:
file=glob.glob('*INDEX*.csv')
file

['H_Dhar_1_1_19-2_12_22-*43* (copy)_INDEX_Mean.csv']

In [3]:
li=[]

In [4]:
for fd in file:
    df=pd.read_csv(fd,index_col=None,header=0)
    li.append(df)
df

                      DATE   PM2.5
0      2019-01-04 12:00:00  208.43
1      2019-01-04 13:00:00  122.23
2      2019-01-04 14:00:00   88.14
3      2019-01-04 15:00:00   85.85
4      2019-01-04 16:00:00   76.94
...                    ...     ...
34260  2022-12-02 00:00:00  157.80
34261  2022-12-02 01:00:00  168.54
34262  2022-12-02 02:00:00  175.81
34263  2022-12-02 03:00:00  180.85
34264  2022-12-02 04:00:00  161.94

[34265 rows x 2 columns]

In [5]:
df['DATE']=pd.DatetimeIndex(df['DATE'])

In [6]:
df=df.set_index('DATE')
df

                      PM2.5
DATE
2019-01-04 12:00:00  208.43
2019-01-04 13:00:00  122.23
2019-01-04 14:00:00   88.14
2019-01-04 15:00:00   85.85
2019-01-04 16:00:00   76.94
...                     ...
2022-12-02 00:00:00  157.80
2022-12-02 01:00:00  168.54
2022-12-02 02:00:00  175.81
2022-12-02 03:00:00  180.85
2022-12-02 04:00:00  161.94

[34265 rows x 1 columns]

In [7]:
df['PM2.5'] = df['PM2.5'].astype('float16')
df

                        PM2.5
DATE
2019-01-04 12:00:00  208.3750
2019-01-04 13:00:00  122.2500
2019-01-04 14:00:00   88.1250
2019-01-04 15:00:00   85.8750
2019-01-04 16:00:00   76.9375
...                       ...
2022-12-02 00:00:00  157.7500
2022-12-02 01:00:00  168.5000
2022-12-02 02:00:00  175.7500
2022-12-02 03:00:00  180.8750
2022-12-02 04:00:00  162.0000

[34265 rows x 1 columns]

In [8]:
s = setup(df, fh = 3500, fold = 5, session_id = 123)

In [14]:
best = compare_models()

In [ ]:
plot_model()

In [ ]:
plot_model(plot='ts')

In [ ]:
df['PM2.5'].plot();

In [ ]:
df.plot();